
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "Mammoth/Localizable.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  },
  {
    "source": "Mammoth/Screens/Registration/mul.lproj/SignUpView.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/Screens/Registration/mul.lproj/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  },
  {
    "source": "Mammoth/Screens/Registration/mul.lproj/SetupProfile.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/Screens/Registration/mul.lproj/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  },
  {
    "source": "Mammoth/Screens/Registration/mul.lproj/SetupInstructionsCell.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/Screens/Registration/mul.lproj/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  },
  {
    "source": "Mammoth/Screens/Registration/mul.lproj/IntroViewController.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/Screens/Registration/mul.lproj/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  },
  {
    "source": "Mammoth/Screens/Registration/mul.lproj/EmailVerificationView.xcstrings",
    "translation": ".i18n/%locale%/Mammoth/Screens/Registration/mul.lproj/%original_file_name%",
    "skip_untranslated_strings": true,
    "skip_untranslated_files": true,
    "export_only_approved": true
  }
]
