name: Crowdin Upload

on:
  push:
    paths: [ '*.xcstring' ]
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Crowdin push
      uses: crowdin/github-action@v1
      with:
        upload_sources: true
        upload_translations: true
        download_translations: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}