name: Crowdin manual upload

on:
  workflow_dispatch:

jobs:
  upload-to-crowdin:
    if: contains('["bdecrem","bnolens", "derspyy", "rileyhCode", "jtomchak"]', github.actor)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Crowdin push
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
        upload_translations: false
        download_translations: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}